version: "3.5"

services:
  haproxy:
    image: couchdb:3.1.1
    container_name: couchdb
    environment:
# Admin username/password.
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    ports:
      - "5984:5984"
    volumes:
      - ./data:/opt/couchdb/data
      - ./local.d:/opt/couchdb/etc/local.d
    restart: unless-stopped