version: "3.5"

services:
  haproxy:
    image: haproxy:2.1.2-alpine
    container_name: haproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy:ro
    networks:
      access-platform:
        ipv4_address: 172.30.0.2
networks:
  access-platform:
    name: access-platform
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
