version: "3.9"

services:
  couchdb:
    profiles:
      - dev
    container_name: access-couch
    image: couchdb:3.1
    env_file:
      - .env.docker
    networks:
      access-platform:
        ipv4_address: 172.30.0.6
        aliases:
          - couch
    ports:
      - "5984:5984"
  package-watcher:
    profiles:
      - dev
    container_name: access-packages
    build:
      context: .
      target: package_watch
    image: access-packages:dev
    volumes:
      - .:/repo
    networks:
      access-platform:
  kivik-watcher:
    profiles:
      - dev
    container_name: access-kivik
    build:
      context: .
      target: kivik_watch
    image: access-kivik:dev
    depends_on:
      - package-watcher
      - couchdb
    volumes:
      - .:/repo
    networks:
      access-platform:
  lapin-dev:
    profiles:
      - dev
    container_name: access-lapin
    build:
      context: .
      target: lapin_dev
    image: access-lapin:dev
    depends_on:
      - package-watcher
      - couchdb
    volumes:
      - .:/repo
    networks:
      access-platform:
        ipv4_address: 172.30.0.9
        aliases:
          - lapin
    ports:
      - "5858:5858"

networks:
  access-platform:
    external: true
