version: "3.5"

services:
  haproxy:
    image: haproxy:2.2-alpine
    container_name: haproxy
    ports:
      - "80:80"
      - "443:443"
      - "10000:10000"
      - "14747:14747"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./certs:/usr/local/etc/haproxy/certs:ro
      - ./error:/usr/local/etc/haproxy/error:ro
    restart: unless-stopped
    networks:
      access-platform:
        ipv4_address: 172.30.0.2
networks:
  access-platform:
    name: access-platform
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
