import { z } from "zod";
import { UnixFilePath } from "../util/UnixFilePath.js";
import { Identified } from "./traits/Identified.js";
import { FileRef } from "./util/FileRef.js";
import { ImageRef } from "./util/ImageRef.js";

/**
 * The virtual representation of the space taken up by a page of a Manifest.
 */
export const Canvas = z
  .object({
    type: z.enum(["canvas"]),

    /**
     * Source information for this Canvas.
     */
    source: z.union([
      /**
       * The Canvas is sourced from our legacy repository.
       */
      z.object({
        from: z.enum(["cihm"]),

        /**
         * File path in the legacy repository.
         */
        path: UnixFilePath,
      }),

      /**
       * The canvas is sourced from an Archivematica repository.
       */
      z.object({
        from: z.enum(["am"]),

        /**
         * Archivematica AIP id.
         */
        aipId: z.string(),

        /**
         * Archivematica object id.
         */
        objId: z.string(),
      }),
    ]),

    /**
     * Reference to an image in the legacy repository, for now.
     */
    master: ImageRef,

    /**
     * If the canvas has been taken down from public view, this is the reason why.
     */
    takedown: z
      .enum(["copyright", "privacy", "traditional_knowledge", "other"])
      .optional(),

    /**
     * Reference to the PDF file generated by OCR.
     */
    ocrPdf: FileRef.optional(),

    /**
     * OCR XML type. One of `alto` or `txtmap`.
     */
    ocrType: z.enum(["alto", "txtmap"]),

    /**
     * As time goes on or errors take place, some canvases may no longer be
     * referenced by a manifest. These canvases may be marked as orphans by setting
     * this flag.
     */
    orphan: z.boolean().optional(),
  })
  .merge(Identified);

export type Canvas = z.infer<typeof Canvas>;

/**
 * The staff-editable properties of a Canvas.
 */
export const EditableCanvas = Canvas.pick({ takedown: true });

export type EditableCanvas = z.infer<typeof EditableCanvas>;
