import { JSONSchemaType } from "ajv";
import Noid, { format as noidFormat } from "../../Format/Noid";
import Text, { schema as textSchema } from "../../Util/Text";
import FileRef, { schema as fileSchema } from "../../Util/FileRef";
import Manifest, { schema as manifestSchema } from "../Manifest";

interface Canvas {
  id: Noid;
  /**
   * The canvas's label in the context of this manifest.
   */
  label: Text;
}

interface Local {
  from: "canvases";
  /**
   * The manifest's canvas list.
   */
  canvases: Canvas[];
  /**
   * Information about the derivative PDF generated by OCR.
   * If path is not specified, a file should exist in the
   * access object store at $id.pdf
   */
  ocrPdf?: FileRef;
}

export default interface CanvasManifest extends Manifest, Local {}

export const schema = manifestSchema.mergeInto(
  {
    $id: "/access/manifest/canvases.json",
    title: "Canvas Manifest",
    type: "object",
    properties: {
      from: { type: "string", const: "canvases" },
      canvases: {
        type: "array",
        items: {
          type: "object",
          properties: {
            id: noidFormat.schema.inline,
            label: textSchema.inline,
          },
          required: ["id", "label"],
        },
      },
      ocrPdf: { ...fileSchema.inline, nullable: true },
    },
    required: ["from", "canvases"],
  } as JSONSchemaType<Local>,
  true
);
